### ISSUE TITLE
App crash: kakao init

### ISSUE THREAD

**Issue by shindonghwi** [Sangmeebee/SearchMovieWithCleanArchitecture#2]
![image](https://user-images.githubusercontent.com/45490440/194851477-51d33df5-c43f-42c0-a1a0-6ff4d3bd184f.png)

Readme.md에 앱 설치 후, Kakao Key 등록방법 작성해주시면 더 좋을 것 같아요 :)
또는 샘플 키 제공해주시면 사용하기에 편할거 같아요!

샘플 앱 공유 감사드립니다 !

**Comment by Sangmeebee** [comment]
좋은 의견 감사합니다~
